# render.yaml
# Defines the services for your Slippy Chat application on Render.

services:
  # Backend Web Service (Flask with Socket.IO)
  - type: web
    name: slippy-chat-backend
    env: python
    rootDirectory: backend/
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:socketio --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1
    envVars:
      - key: FRONTEND_URL
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: REDIS_URL # Optional
        sync: false
    autoDeploy: true
    plan: starter

  # Frontend Static Site (React/Vite)
  - type: static_site   # ✅ Correct type
    name: slippy-chat-frontend
    rootDirectory: frontend/  # ✅ Ensure this matches your actual folder
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_REACT_APP_API_URL
        sync: false
    autoDeploy: true
