# render.yaml
services:
  # Backend Web Service (Flask with Socket.IO)
  - type: web
    name: slippy-chat-backend
    env: python
    rootDirectory: backend/
    buildCommand: pip install -r requirements.txt
    # IMPORTANT CHANGE HERE: Use the eventlet WSGI server directly
    # 'app:app' refers to the Flask app instance in app.py
    startCommand: eventlet.wsgi.server(eventlet.listen(('0.0.0.0', 10000)), app)
    # Render maps internal port 10000 to external HTTP/S
    envVars:
      - key: FRONTEND_URL
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: REDIS_URL
        sync: false
    autoDeploy: true
    plan: starter

  # Frontend Static Site (React/Vite)
  - type: static
    name: slippy-chat-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_REACT_APP_API_URL
        sync: false
    autoDeploy: true
